name: Feature
description: New functionality or improvement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe the ideal behavior
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: UI
        - label: API
        - label: Auth
        - label: Performance
        - label: SEO
        - label: DX / Tooling
